version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "pnpm"
