export const buttonStyles = {
  'html.light &': {
    '--theme-button-options-background-color': '#f7f7f7',
    '--theme-button-options-background-color-hover': '#f7f7f7',
    '--theme-button-options-border-color': '#e2e0e7',
    '--theme-button-options-border-color-hover': '#b2b4d0',
    '--theme-button-options-color': '#4b4d60',
    '--theme-button-options-color-hover': '#4b4d60',
    '--theme-button-options-background-color-disabled': '#f7f7f7',
    '--theme-button-options-border-color-disabled': '#e2e0e7',
    '--theme-button-options-color-disabled': '#4b4d60',
  },
  'html.dark &': {
    '--theme-button-options-background-color': 'transparent',
    '--theme-button-options-background-color-hover': 'transparent',
    '--theme-button-options-border-color': '#c5c2cb',
    '--theme-button-options-border-color-hover': '#fff',
    '--theme-button-options-color': '#c5c2cb',
    '--theme-button-options-color-hover': '#fff',
    '--theme-button-options-background-color-disabled': 'transparent',
    '--theme-button-options-border-color-disabled': '#c5c2cb',
    '--theme-button-options-color-disabled': '#c5c2cb',
  },
}

export const dropdownStyles = {
  'html.light &': {
    '--theme-dropdown-background-color': '#fff',
    '--theme-dropdown-border-color': '#fff',
    '--theme-dropdown-box-shadow': '0 0 20px 0 rgb(0 0 0 / 8%)',
    '--theme-dropdown-item-background-color': 'transparent',
    '--theme-dropdown-item-background-color-hover': 'rgb(0 0 0 / 2%)',
    '--theme-dropdown-item-background-color-active': 'rgb(0 0 0 / 5%)',
    '--theme-dropdown-item-color': '#2e3048',
    '--theme-dropdown-item-color-hover': '#2e3048',
    '--theme-dropdown-item-color-active': '#2e3048',
    '--theme-dropdown-item-border-color': '#f0f0f0',
    '--theme-dropdown-item-border-color-hover': '#f0f0f0',
    '--theme-dropdown-item-border-color-active': '#f0f0f0',
  },
  'html.dark &': {
    '--theme-dropdown-background-color': '#292b43',
    '--theme-dropdown-border-color': '#292b43',
    '--theme-dropdown-box-shadow': '0 9.6px 13px 0 rgb(0 0 0 / 8%)',
    '--theme-dropdown-item-background-color': 'transparent',
    '--theme-dropdown-item-background-color-hover': 'rgb(255 255 255 / 2%)',
    '--theme-dropdown-item-background-color-active': 'rgb(255 255 255 / 5%)',
    '--theme-dropdown-item-color': '#fff',
    '--theme-dropdown-item-color-hover': '#fff',
    '--theme-dropdown-item-color-active': '#fff',
    '--theme-dropdown-item-border-color': '#4b4d60',
    '--theme-dropdown-item-border-color-hover': '#4b4d60',
    '--theme-dropdown-item-border-color-active': '#4b4d60',
  },
}
