export const styles = {
  'html.light &': {
    '--background-color': '#fff',
    '--border-color': '#fff',
    '--title-color': '#2e3048',
    '--box-shadow': '0 9.6px 13px 0 rgb(0 0 0 / 8%)',
    '--network-button-color': '#2e3048',
    '--network-button-background-color': '#f7f7f7',
    '--list-border-top-color': '#e2e0e7',
    '--row-background-color': 'transparent',
    '--row-background-color-hover': 'rgb(0 0 0 / 5%)',
    '--row-token-name-color': '#2e3048',
    '--row-token-balance-color': '#2e3048',
    '--row-token-value-color': '#2e3048',
    '--top-token-item-background-color': '#fff',
    '--top-token-item-border-color': '#e2e0e7',
    '--top-token-item-color': '#2e3048',
    '--top-token-item-background-color-hover': 'rgb(0 0 0 / 5%)',
    '--search-field-color': '#2e3048',
    '--search-field-color-active': '#2e3048',
    '--search-field-background-color': '#f7f7f7',
    '--search-field-background-color-active': '#f7f7f7',
    '--search-field-placeholder-color': '#161d1a',
    '--search-field-box-shadow': 'none',
    '--search-field-box-shadow-active': 'rgb(0 0 0 / 10%)',
    '--search-field-border-color': '#e2e0e7',
    '--search-field-border-color-active': '#e2e0e7',
    '--add-erc20-token-button-background-color': '#2e3048',
    '--add-erc20-token-button-background-color-hover': '#3d405f',
    '--add-erc20-token-button-border-color': '#2e3048',
    '--add-erc20-token-button-border-color-hover': '#3d405f',
    '--add-erc20-token-button-color': '#fff',
    '--add-erc20-token-button-color-hover': '#fff',
  },
  'html.dark &': {
    '--background-color': '#2e3048',
    '--border-color': '#2e3048',
    '--title-color': '#fff',
    '--box-shadow': '0 0 20px 0 rgb(255 255 255 / 8%)',
    '--network-button-color': '#fff',
    '--network-button-background-color': '#292b43',
    '--list-border-top-color': '#4b4d60',
    '--row-background-color': 'transparent',
    '--row-background-color-hover': 'rgb(255 255 255 / 5%)',
    '--row-token-name-color': '#fff',
    '--row-token-balance-color': '#fff',
    '--row-token-value-color': '#fff',
    '--top-token-item-background-color': '#2e3048',
    '--top-token-item-border-color': '#4b4d60',
    '--top-token-item-color': '#fff',
    '--top-token-item-background-color-hover': 'rgb(255 255 255 / 5%)',
    '--search-field-color': '#fff',
    '--search-field-color-active': '#fff',
    '--search-field-background-color': '#292b43',
    '--search-field-background-color-active': '#292b43',
    '--search-field-placeholder-color': '#ddd',
    '--search-field-box-shadow': 'none',
    '--search-field-box-shadow-active': 'none',
    '--search-field-border-color': '#5f6178',
    '--search-field-border-color-active': '#5f6178',
    '--add-erc20-token-button-background-color': '#5f6178',
    '--add-erc20-token-button-background-color-hover': '#4a4c5f',
    '--add-erc20-token-button-border-color': '#5f6178',
    '--add-erc20-token-button-border-color-hover': '#4a4c5f',
    '--add-erc20-token-button-color': '#fff',
    '--add-erc20-token-button-color-hover': '#fff',
  },
}

export default styles
