export const styles = {
  'html.light &': {
    '--theme-token-input-title-color': '#2e3048',
    '--theme-token-input-background': '#fff',
    '--theme-token-input-textfield-background-color': '#fff',
    '--theme-token-input-textfield-background-color-active': 'rgb(0 0 0 / 5%)',
    '--theme-token-input-textfield-border-color': '#e2e0e7',
    '--theme-token-input-textfield-border-color-active': '#e2e0e7',
    '--theme-token-input-textfield-color': '#2e3048',
    '--theme-token-input-textfield-color-active': '#2e3048',
    '--theme-token-input-textfield-placeholder-color': 'rgb(22 29 26 / 60%)',
    '--theme-token-input-dropdown-button-background-color': '#fff',
    '--theme-token-input-dropdown-button-background-color-hover': 'rgb(0 0 0 / 5%)',
    '--theme-token-input-dropdown-button-border-color': '#e2e0e7',
    '--theme-token-input-dropdown-button-border-color-hover': '#e2e0e7',
    '--theme-token-input-dropdown-button-border-color-active': '#e2e0e7',
    '--theme-token-input-dropdown-button-color': '#2e3048',
    '--theme-token-input-dropdown-button-color-hover': '#2e3048',
    '--theme-token-input-dropdown-button-background-color-disabled': '#fff',
    '--theme-token-input-dropdown-button-border-color-disabled': '#e2e0e7',
    '--theme-token-input-dropdown-button-color-disabled': '#2e3048',
    '--theme-token-input-max-button-background-color': '#fff',
    '--theme-token-input-max-button-background-color-hover': 'rgb(0 0 0 / 5%)',
    '--theme-token-input-max-button-border-color': '#e2e0e7',
    '--theme-token-input-max-button-border-color-hover': '#e2e0e7',
    '--theme-token-input-max-button-border-color-active': '#e2e0e7',
    '--theme-token-input-max-button-color': '#8b46a4',
    '--theme-token-input-max-button-color-hover': '#8b46a4',
    '--theme-token-input-max-button-background-color-disabled': '#fff',
    '--theme-token-input-max-button-border-color-disabled': '#e2e0e7',
    '--theme-token-input-max-button-color-disabled': '#8b46a4',
    '--theme-token-input-estimated-usd-color': '#4b4d60',
    '--theme-token-input-balance-color': '#4b4d60',
  },
  'html.dark &': {
    '--theme-token-input-title-color': '#fff',
    '--theme-token-input-background': '#373954',
    '--theme-token-input-textfield-background-color': '#373954',
    '--theme-token-input-textfield-background-color-active': 'rgb(255 255 255 / 5%)',
    '--theme-token-input-textfield-border-color': '#5f6178',
    '--theme-token-input-textfield-border-color-active': '#5f6178',
    '--theme-token-input-textfield-color': 'rgb(255 255 255 / 80%)',
    '--theme-token-input-textfield-color-active': 'rgb(255 255 255 / 80%)',
    '--theme-token-input-textfield-placeholder-color': 'rgb(255 255 255 / 50%)',
    '--theme-token-input-dropdown-button-background-color': '#373954',
    '--theme-token-input-dropdown-button-background-color-hover': 'rgb(255 255 255 / 5%)',
    '--theme-token-input-dropdown-button-border-color': '#5f6178',
    '--theme-token-input-dropdown-button-border-color-hover': '#5f6178',
    '--theme-token-input-dropdown-button-border-color-active': '#5f6178',
    '--theme-token-input-dropdown-button-color': '#fff',
    '--theme-token-input-dropdown-button-color-hover': '#fff',
    '--theme-token-input-dropdown-button-background-color-disabled': '#373954',
    '--theme-token-input-dropdown-button-border-color-disabled': '#5f6178',
    '--theme-token-input-dropdown-button-color-disabled': '#fff',
    '--theme-token-input-max-button-background-color': '#373954',
    '--theme-token-input-max-button-background-color-hover': 'rgb(255 255 255 / 5%)',
    '--theme-token-input-max-button-border-color': '#c5c2cb',
    '--theme-token-input-max-button-border-color-hover': '#c5c2cb',
    '--theme-token-input-max-button-border-color-active': '#c5c2cb',
    '--theme-token-input-max-button-color': '#c5c2cb',
    '--theme-token-input-max-button-color-hover': '#fff',
    '--theme-token-input-max-button-background-color-disabled': '#373954',
    '--theme-token-input-max-button-border-color-disabled': '#5f6178',
    '--theme-token-input-max-button-color-disabled': '#fff',
    '--theme-token-input-estimated-usd-color': '#e2e0e7',
    '--theme-token-input-balance-color': '#e2e0e7',
  },
}

export default styles
