export const styles = {
  'html.light &': {
    '--title-color': '#2e3048',
    '--background': '#fff',
    '--textfield-background-color': '#fff',
    '--textfield-background-color-active': 'rgb(0 0 0 / 5%)',
    '--textfield-border-color': '#e2e0e7',
    '--textfield-border-color-active': '#e2e0e7',
    '--textfield-color': '#2e3048',
    '--textfield-color-active': '#2e3048',
    '--textfield-placeholder-color': 'rgb(22 29 26 / 60%)',
    '--dropdown-button-background-color': '#fff',
    '--dropdown-button-background-color-hover': 'rgb(0 0 0 / 5%)',
    '--dropdown-button-border-color': '#e2e0e7',
    '--dropdown-button-border-color-hover': '#e2e0e7',
    '--dropdown-button-border-color-active': '#e2e0e7',
    '--dropdown-button-color': '#2e3048',
    '--dropdown-button-color-hover': '#2e3048',
    '--dropdown-button-background-color-disabled': '#fff',
    '--dropdown-button-border-color-disabled': '#e2e0e7',
    '--dropdown-button-color-disabled': '#2e3048',
    '--max-button-background-color': '#fff',
    '--max-button-background-color-hover': 'rgb(0 0 0 / 5%)',
    '--max-button-border-color': '#e2e0e7',
    '--max-button-border-color-hover': '#e2e0e7',
    '--max-button-border-color-active': '#e2e0e7',
    '--max-button-color': '#8b46a4',
    '--max-button-color-hover': '#8b46a4',
    '--max-button-background-color-disabled': '#fff',
    '--max-button-border-color-disabled': '#e2e0e7',
    '--max-button-color-disabled': '#8b46a4',
    '--estimated-usd-color': '#4b4d60',
    '--balance-color': '#4b4d60',
  },
  'html.dark &': {
    '--title-color': '#fff',
    '--background': '#373954',
    '--textfield-background-color': '#373954',
    '--textfield-background-color-active': 'rgb(255 255 255 / 5%)',
    '--textfield-border-color': '#5f6178',
    '--textfield-border-color-active': '#5f6178',
    '--textfield-color': 'rgb(255 255 255 / 80%)',
    '--textfield-color-active': 'rgb(255 255 255 / 80%)',
    '--textfield-placeholder-color': 'rgb(255 255 255 / 50%)',
    '--dropdown-button-background-color': '#373954',
    '--dropdown-button-background-color-hover': 'rgb(255 255 255 / 5%)',
    '--dropdown-button-border-color': '#5f6178',
    '--dropdown-button-border-color-hover': '#5f6178',
    '--dropdown-button-border-color-active': '#5f6178',
    '--dropdown-button-color': '#fff',
    '--dropdown-button-color-hover': '#fff',
    '--dropdown-button-background-color-disabled': '#373954',
    '--dropdown-button-border-color-disabled': '#5f6178',
    '--dropdown-button-color-disabled': '#fff',
    '--max-button-background-color': '#373954',
    '--max-button-background-color-hover': 'rgb(255 255 255 / 5%)',
    '--max-button-border-color': '#c5c2cb',
    '--max-button-border-color-hover': '#c5c2cb',
    '--max-button-border-color-active': '#c5c2cb',
    '--max-button-color': '#c5c2cb',
    '--max-button-color-hover': '#fff',
    '--max-button-background-color-disabled': '#373954',
    '--max-button-border-color-disabled': '#5f6178',
    '--max-button-color-disabled': '#fff',
    '--estimated-usd-color': '#e2e0e7',
    '--balance-color': '#e2e0e7',
  },
}

export default styles
