#!/bin/sh

# From conventional commits, forces to follow the commit convention.
# Check https://github.com/conventional-changelog/commitlint for more.
echo "Running commitlint"
pnpm commitlint --edit "$1"
